### ISSUE TITLE
star this repo

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/ProDesigner#3]
screenshot on comments

**Comment by YashRE42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34877059-668341f6-f7ca-11e7-977a-7b2170fef310.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-12 make a logo issue 4 opencode18 prodesigner](https://user-images.githubusercontent.com/28799332/34882888-ecf125e2-f7dd-11e7-9ea7-5311248f6887.png)

**Comment by nikki1016** [comment]
![star4](https://user-images.githubusercontent.com/26041681/34891410-7ed9a02a-f7fb-11e7-811b-4b836a7404c3.png)

**Comment by gauthamzz** [comment]
Wow google summer of code is bookmarked 🙈

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34903462-fa6fae9e-f857-11e7-8f8f-8d62aa135eef.png)

**Comment by atisayajain** [comment]
![capture](https://user-images.githubusercontent.com/19758073/34904292-1513d7fa-f869-11e7-81bf-84ebebc01196.PNG)

**Comment by arpitmisraw** [comment]
![screenshot from 2018-01-14 00-00-15](https://user-images.githubusercontent.com/32339738/34908912-0480a918-f8be-11e7-9b86-2e936e833033.png)

**Comment by pani-vishal** [comment]
![star1](https://user-images.githubusercontent.com/30634978/36043842-b329f95e-0df6-11e8-99d5-ace142a1ee90.png)
